Integrate login
CS3219-AY2324S1/ay2324s1-course-assessment-g13 pull request #19
Opened 2023-09-17 13:59 UTC by ThomasHoooo

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Summary of PR

Integrated login, register with the backend

## Details

@JovonLim please help to refactor your code at questions (frontend) to use a more reusable http method.

## [Optional] Screenshots, Recordings

2023-09-18 13:04 UTC, rexong requested changes

2023-09-18 13:04 UTC, rexong commented on frontend/app/components/modal/signupModal.tsx
> +              /> */}
still need this comment out portion?

2023-09-18 13:04 UTC, rexong commented on frontend/app/components/modal/loginModal.tsx
> +    console.log(response); //add in your api call to check login
can remove this console.log

2023-09-19 13:56 UTC, ThomasHoooo commented on frontend/app/components/modal/loginModal.tsx
> +    console.log(response); //add in your api call to check login
good catch, thanks!

2023-09-19 14:06 UTC, Ugholaf approved these changes
Just remove those console logs

2023-09-19 14:06 UTC, Ugholaf commented on frontend/app/axios/axios.tsx
>    try {
is this repeated? Actually, yours is better, more general. If is the same and I can remove it in my PR

2023-09-19 14:46 UTC, merged