[WIP] Create docker compose at root
CS3219-AY2324S1/ay2324s1-course-assessment-g13 pull request #8
Opened 2023-09-09 07:52 UTC by yeo-yiheng

This PR aims to bundle all individual microservice containers into a single docker-compose file in the project root, where it will be simple to run `docker compose up` to get all container instances up and running. Additionally, this allows us to start containers up based on some imposed ordering, which can be defined later on in the timeline.

2023-09-09 13:59 UTC, ThomasHoooo commented on backend/collaboration-service/Dockerfile
> +FROM golang:1.20
Just a nit: it would be better if we can keep the image size small, and alpine versions are usually the best options. You can take reference from my Dockerfile as we are doing the same thing :)

2023-09-09 14:00 UTC, ThomasHoooo reviewed
Thanks for creating all the necessary files!

2023-09-09 16:46 UTC, yeo-yiheng commented on backend/collaboration-service/Dockerfile
> +FROM golang:1.20
Agreed that it is important to keep image size small. Thanks for the reference, I'll cross check with yours and do that!

2023-09-15 06:37 UTC, ThomasHoooo commented on backend/user-service/bin/air
Can I check why is this file committed?

2023-09-15 06:40 UTC, ThomasHoooo commented on backend/question-service/Dockerfile.stage
Just a nit: I don't think we have staging environment, should it be dev instead?

2023-09-15 06:41 UTC, ThomasHoooo commented on backend/matching-service/main.go
> +}
I think it might be better to standardize and use echo since we are already using it

2023-09-17 07:39 UTC, yeo-yiheng commented on backend/user-service/bin/air
Oh crap i missed it, thanks ill remove it!

2023-09-17 07:41 UTC, yeo-yiheng commented on backend/question-service/Dockerfile.stage
Hmm if we are going down to terminologies then yes, it should be dev because technically we dont have any prod env to emulate. I use it interchangeably in environments where staging and dev are not exactly concretely defined. But I'll change it to dev just for more clarity

2023-09-17 07:41 UTC, yeo-yiheng commented on backend/matching-service/main.go
> +}
Agreed, I'll swap framework to echo, good catch

2023-09-20 08:18 UTC, ThomasHoooo commented on .github/workflows/lint.yaml
> +      - '**/.gitignore'
Please help to remove all these lines, all files should have a new line at eof

2023-09-20 08:21 UTC, ThomasHoooo commented on docker-compose.yaml
> +      dockerfile: backend/collaboration-service/Dockerfile.dev
context already addresses the location for the Dockerfile.

```diff
-    dockerfile: backend/collaboration-service/Dockerfile.dev
+   Dockerfile.dev
```

The other services also apply.

2023-09-20 08:39 UTC, ThomasHoooo commented on docker-compose.yaml
> +      - .:/usr/src/app
You are copying the whole root directory into `/usr/src/app`, you can change it to `./backend/collaboration-service:/usr/scr/app`

The other services apply also

2023-09-20 08:40 UTC, ThomasHoooo commented on docker-compose.yaml
> +      - db-data:/data/db
It might be btr to rename this volume as `questions-db`?

2023-09-20 09:34 UTC, yeo-yiheng commented on docker-compose.yaml
> +      - .:/usr/src/app
Agreed on this, thanks for spotting this!

2023-09-20 09:34 UTC, yeo-yiheng commented on docker-compose.yaml
> +      dockerfile: backend/collaboration-service/Dockerfile.dev
Changed, thanks!

2023-09-20 09:35 UTC, yeo-yiheng commented on .github/workflows/lint.yaml
> +      - '**/.gitignore'
Roger, removed

2023-09-20 09:44 UTC, ThomasHoooo reviewed
I actually have a few concerns regarding the frontend files. I am afraid that this PR will overwrite all the frontend files should this PR be merged in, and it may cause unexpected behaviours, and the newer frontend files at the master branch will get overwritten.

2023-09-20 09:53 UTC, yeo-yiheng commented
> I actually have a few concerns regarding the frontend files. I am afraid that this PR will overwrite all the frontend files should this PR be merged in, and it may cause unexpected behaviours, and the newer frontend files at the master branch will get overwritten.

Before merge, I'll first merge master into my branch. This should allow me to resolve any potential merge conflicts regarding overwriting of files.

2023-10-05 06:26 UTC, rexong commented
There is a merge conflict that didn't surface in `/backend/api-gateway/docker-compose.yml` when merging from master.

2023-10-05 06:28 UTC, rexong requested changes

2023-10-05 06:28 UTC, rexong commented on backend/api-gateway/docker-compose.yaml
I think there is a merge conflict here that did not surface when merged

2023-10-05 06:36 UTC, yeo-yiheng commented on backend/api-gateway/docker-compose.yaml
Thanks for pointing this out, I'll fix this in a bit. Not sure why this didn't surface on my side

2023-10-05 07:56 UTC, ThomasHoooo commented on backend/question-service/config/config.go
> +	log.Println(MONGO_URI)
This has to be removed in the future

2023-10-05 07:58 UTC, ThomasHoooo reviewed
I think the docker compose files in the respective services are not needed anymore, so we can clean up those files to avoid confusions?

2023-10-07 10:57 UTC, merged